[workspace.package]
version = "0.5.5"
edition = "2024"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/aldialimucaj/palo"
repository = "https://github.com/aldialimucaj/palo"
keywords = ["orchestration", "developer-tools", "cli", "workspace", "tui"]
categories = ["command-line-utilities", "development-tools"]

[workspace]
members = [
    "palo-core",
    "palo",
    "palo-projects",
    "palo-tui",
]
resolver = "3"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
